export const MAIN_CATEGORIES_ARRAY = [
  /*  1   */ { name: 'Administracja' },
  /*  2   */ { name: 'Budownictwo' },
  /*  3   */ { name: 'Elektronika' },
  /*  4   */ { name: 'Finanse' },
  /*  5   */ { name: 'Gastronomia' },
  /*  6   */ { name: 'Górnictwo' },
  /*  7   */ { name: 'Informatyka' },
  /*  8   */ { name: 'Medycyna' },
  /*  9   */ { name: 'Motoryzacja' },
  /*  10  */ { name: 'Logistyka' },
  /*  11  */ { name: 'Przemysł' },
  /*  12  */ { name: 'Rolnictwo' },
  /*  13  */ { name: 'Sprzedaż' },
  /*  14  */ { name: 'Turystyka' },
  /*  15  */ { name: 'Uroda' },
  /*  16  */ { name: 'Usługi' },
];

export const CATEGORIES_ARRAY = [
  { name: 'Technik administracji', parentId: 1 },
  { name: 'Technik archiwista', parentId: 1 },
  { name: 'Technikprac biurowych', parentId: 1 },
  { name: 'Recepcjonista', parentId: 1 },
  { name: 'Blacharz', parentId: 2 },
  { name: 'Cieśla', parentId: 2 },
  { name: 'Dekarz', parentId: 2 },
  { name: 'Murarz', parentId: 2 },
  { name: 'Technik budownictwa', parentId: 2 },
  { name: 'Elektronik', parentId: 3 },
  { name: 'Elektryk', parentId: 3 },
  { name: 'Monter sieci i urządzeń telekomunikacyjnych', parentId: 3 },
  { name: 'Technik mechatronik', parentId: 3 },
  { name: 'Analityk', parentId: 4 },
  { name: 'Księgowy', parentId: 4 },
  { name: 'Technik ekonomista', parentId: 4 },
  { name: 'Technik rachunkowości', parentId: 4 },
  { name: 'Cukiernik', parentId: 5 },
  { name: 'Dietetyk', parentId: 5 },
  { name: 'Kelner', parentId: 5 },
  { name: 'Kucharz', parentId: 5 },
  { name: 'Piekarz', parentId: 5 },
  { name: 'Technik energetyk', parentId: 6 },
  { name: 'Technik gazownictwa', parentId: 6 },
  { name: 'Technik górnictwa odkrywkowego', parentId: 6 },
  { name: 'Technik górnictwa podziemnego', parentId: 6 },
  { name: 'Technik informatyk', parentId: 7 },
  { name: 'Technik programista', parentId: 7 },
  { name: 'Technik teleinformatyk', parentId: 7 },
  { name: 'Technik telekomunikacji', parentId: 7 },
  { name: 'Higienistka stomatologiczna', parentId: 8 },
  { name: 'Opiekun medyczny', parentId: 8 },
  { name: 'Technik farmaceutyczny', parentId: 8 },
  { name: 'Ratownik medyczny', parentId: 8 },
  { name: 'Blacharz samochodowy', parentId: 9 },
  { name: 'Lakiernik samochodowy', parentId: 9 },
  { name: 'Mechanik motocyklowy', parentId: 9 },
  { name: 'Mechanik pojazdów samochodowych', parentId: 9 },
  { name: 'Magazynier logistyk', parentId: 10 },
  { name: 'Spedytor', parentId: 10 },
  { name: 'Technik logistyk', parentId: 10 },
  { name: 'Technik spedytor', parentId: 10 },
  { name: 'Technik przemysłu metalurgicznego', parentId: 11 },
  { name: 'Technik technologii ceramicznej', parentId: 11 },
  { name: 'Technik technologii chemicznej', parentId: 11 },
  { name: 'Technik włókiennik', parentId: 11 },
  { name: 'Ogrodnik', parentId: 12 },
  { name: 'Rolnik', parentId: 12 },
  { name: 'Technik architektury krajobrazu', parentId: 12 },
  { name: 'Technik leśnik', parentId: 12 },
  { name: 'Technik handlowiec', parentId: 13 },
  { name: 'Technik księgarstwa', parentId: 13 },
  { name: 'Technik organizacji reklamy', parentId: 13 },
  { name: 'Sprzedawca', parentId: 13 },
  { name: 'Technik hotelarstwa', parentId: 14 },
  { name: 'Pracownik obsługi hotelowej', parentId: 14 },
  { name: 'Technik organizacji turystyki', parentId: 14 },
  { name: 'Technik turystyki wiejskiej', parentId: 14 },
  { name: 'Fryzjer', parentId: 15 },
  { name: 'Technik usług kosmetycznych', parentId: 15 },
  { name: 'Technik stylista', parentId: 15 },
  { name: 'Sprzedawca', parentId: 15 },
  { name: 'Fotgraf', parentId: 16 },
  { name: 'Jubiler', parentId: 16 },
  { name: 'Kominiarz', parentId: 16 },
  { name: 'Zegarmistrz', parentId: 16 },
];
