export const ROUTER_PATHS = {
  ACTIVATION: '/activation',
  APPLICATIONS: '/aplications',
  AUTH: '/auth',
  COMPANIES: '/companies',
  CREATE_COMPANY: '/create-company',
  COMPANY: '/my-company',
  COMPANY_UPDATE: '/my-company/update',
  COMPANY_UPLOAD: '/my-company/upload-images',
  CREATE_BRANCH: '/my-company/branches/create',
  COMPANY_OFFER_CREATE: '/my-offers/create',
  COMPANY_OFFER_UPDATE: '/my-offers/:offerId/update',
  COMPANY_OFFERS: '/my-offers',
  COMPANY_OFFER: '/my-offers/:offerId',
  UPDATE_BRANCH: '/my-company/branches',
  OFFERS: '/offers',
  USERS: '/USERS',
  POST_AUTH: '/post-auth',
  PROFILE: '/profile',
  RESET: '/reset',
};
