export const ROUTER_PATHS = {
  ACTIVATION: '/activation',
  APPLICATIONS: '/aplications',
  AUTH: '/auth',
  COMPANIES: '/companies',
  COMPANY: '/company',
  COMPANY_UPDATE: '/company/update',
  COMPANY_UPLOAD: '/company/upload-images',
  CREATE_COMPANY: '/create-company',
  CREATE_BRANCH: '/company/branches/create',
  COMPANY_OFFER_CREATE: '/company/offers/create',
  COMPANY_OFFER_UPDATE: '/company/offers/:offerId/update',
  COMPANY_OFFER: '/company/offers/:offerId',
  UPDATE_BRANCH: '/company/branches',
  OFFERS: '/offers',
  USERS: '/USERS',
  POST_AUTH: '/post-auth',
  PROFILE: '/profile',
  RESET: '/reset',
};
